module.exports = {
    PLUGINID: 'TPSpotifyPG',
    PLUGINURL: 'https://github.com/pratikghodasara/tp-spotify-pg',
    PLUGINUPDATEURL: 'https://raw.githubusercontent.com/pratikghodasara/tp-spotify-pg/master/package.json',
    PLUGINRELEASEURL: 'https://github.com/pratikghodasara/tp-spotify-pg/releases',
    START_CAPTURE_WAIT_TIME: 2,
    SETTING_SPOTIFY_PAGE_NAME: 'Spotify Page Name',
    SETTING_AUTOMATIC_UPDATE: 'Update Spotify State Automatically',
    SETTING_AUTOMATIC_UPDATE_FREQUENCY: 'Automatic Spotify State Update Frequency',
    SETTING_IS_PLAYING_AUTOMATIC_UPDATE: 'Update Is Playing State Automatically',
    SETTING_TRACK_INFO_AUTOMATIC_UPDATE: 'Update Track Info Automatically',
    SETTING_IS_SHUFFLING_AUTOMATIC_UPDATE: 'Update Is Shuffling State Automatically',
    SETTING_IS_REPEATING_AUTOMATIC_UPDATE: 'Update Is Repeating State Automatically',
    SETTING_IS_VOLUME_MUTE_AUTOMATIC_UPDATE: 'Update Is Volume Mute State Automatically',
}
